//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Different
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Link { get; set; }
        public Nullable<int> EstimateNumber { get; set; }
        public Nullable<int> ActualNumber { get; set; }
        public Nullable<int> BackNumber { get; set; }
        public Nullable<System.DateTime> AddTimes { get; set; }
    }
}
