//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkMailboxQuery
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string ReviewLink { get; set; }
        public Nullable<int> State { get; set; }
        public string Grade { get; set; }
        public string Comments { get; set; }
        public string SellerName { get; set; }
        public string BuyerName { get; set; }
        public string BuyerEmail { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
