//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavBySubmeun
    {
        public int Id { get; set; }
        public Nullable<int> ModularId { get; set; }
        public string SubmenuName { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Remark { get; set; }
    }
}
